[package]
name = "minecraft-pinger"
version = "0.1.0"
edition = "2024"

[features]
default = ["java", "bedrock"]

bedrock = []
java = []

[dependencies]
tokio = { version = "1.52.3", features = ["full"] }
serde = { version = "1.0.228", features = ["derive"] }
hickory-resolver = { version = "0.26.1", features = ["tokio"] }

serde_json = "1.0.150"
thiserror = "2.0.18"

bytes = "1.11.1"

csv = "1.4.0"
log = "0.4.31"
regex = "1.11.1"
rand = "0.10.1"
