[package]
name = "minecraft-pinger"
version = "0.1.2"
edition = "2024"
description = "A high-performance, asynchronous Rust library for pinging Minecraft servers to retrieve status, players, and metadata."
license = "MIT"
repository = "https://github.com/Flash303/minecraft-pinger"

authors = ["Flash303"]

[features]
default = ["java", "bedrock"]

bedrock = []
java = []

[dependencies]
tokio = { version = "1.*", features = ["net", "time", "io-util", "rt"] }
serde = { version = "1.0.*", features = ["derive"] }
hickory-resolver = { version = "0.26.*", default-features = false, features = ["tokio"] }

serde_json = "1.*"
thiserror = "2.*"

bytes = "1.*"

log = "0.4.*"
rand = "0.10.*"
